In [2]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [3]:
import numpy as np


In [4]:
# From Python Lists
arr = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
 
# Special Arrays
np.zeros((3, 3))
np.ones((2, 4))
np.eye(3)
np.arange(0, 10, 2)
np.linspace(0, 1, 5)
np.random.rand(3, 2)
np.random.randn(3, 2)


array([[ 1.19688415, -0.25335654],
       [-0.1208039 , -1.49073813],
       [ 0.96935681, -0.08424687]])

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)


(2, 3)
2
6
int64


In [6]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a + b
a * b
np.sin(a)
 
# Matrix Multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)
A @ B
 
# Aggregation
arr = np.array([1, 2, 3, 4])
arr.sum()
arr.mean()
arr.max()
arr.min()
arr.std()


np.float64(1.118033988749895)

In [7]:
arr = np.array([1, 2, 3, 4, 5])
arr[0]
arr[1:4]
arr[::2]
 
# 2D Arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[0, 1]
arr[:, 1]
arr[1, :2]
 
# Boolean Indexing
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3
arr[mask]


array([4, 5])

In [8]:
# Reshape
arr = np.arange(6)
arr.reshape(2, 3)
 
# Concatenation
a = np.array([1, 2])
b = np.array([3, 4])
np.concatenate((a, b))
 
# Stacking
np.vstack((a, b))
np.hstack((a, b))


array([1, 2, 3, 4])

In [9]:
a = np.array([1, 2, 3])
a + 5  # [6, 7, 8]


array([6, 7, 8])

In [10]:
# Save to a file
np.save('array.npy', arr)
 
# Load from a file
loaded_arr = np.load('array.npy')
